// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/hellotencent_service.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloTencentRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Message              string         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *HelloTencentRequest) Reset()         { *m = HelloTencentRequest{} }
func (m *HelloTencentRequest) String() string { return proto.CompactTextString(m) }
func (*HelloTencentRequest) ProtoMessage()    {}
func (*HelloTencentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_065a2c8480f4a8cf, []int{0}
}

func (m *HelloTencentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloTencentRequest.Unmarshal(m, b)
}
func (m *HelloTencentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloTencentRequest.Marshal(b, m, deterministic)
}
func (m *HelloTencentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloTencentRequest.Merge(m, src)
}
func (m *HelloTencentRequest) XXX_Size() int {
	return xxx_messageInfo_HelloTencentRequest.Size(m)
}
func (m *HelloTencentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloTencentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloTencentRequest proto.InternalMessageInfo

func (m *HelloTencentRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *HelloTencentRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type HelloTencentResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Message              string          `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *HelloTencentResponse) Reset()         { *m = HelloTencentResponse{} }
func (m *HelloTencentResponse) String() string { return proto.CompactTextString(m) }
func (*HelloTencentResponse) ProtoMessage()    {}
func (*HelloTencentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_065a2c8480f4a8cf, []int{1}
}

func (m *HelloTencentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloTencentResponse.Unmarshal(m, b)
}
func (m *HelloTencentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloTencentResponse.Marshal(b, m, deterministic)
}
func (m *HelloTencentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloTencentResponse.Merge(m, src)
}
func (m *HelloTencentResponse) XXX_Size() int {
	return xxx_messageInfo_HelloTencentResponse.Size(m)
}
func (m *HelloTencentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloTencentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloTencentResponse proto.InternalMessageInfo

func (m *HelloTencentResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *HelloTencentResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloTencentRequest)(nil), "api.HelloTencentRequest")
	proto.RegisterType((*HelloTencentResponse)(nil), "api.HelloTencentResponse")
}

func init() { proto.RegisterFile("api/hellotencent_service.proto", fileDescriptor_065a2c8480f4a8cf) }

var fileDescriptor_065a2c8480f4a8cf = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4b, 0x2c, 0xc8, 0xd4,
	0xcf, 0x48, 0xcd, 0xc9, 0xc9, 0x2f, 0x49, 0xcd, 0x4b, 0x4e, 0xcd, 0x2b, 0x89, 0x2f, 0x4e, 0x2d,
	0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x94,
	0x12, 0x01, 0x29, 0x2a, 0x2a, 0x48, 0x8e, 0x4f, 0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0x83, 0x48, 0x29,
	0x45, 0x73, 0x09, 0x7b, 0x80, 0x34, 0x86, 0x40, 0x34, 0x06, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97,
	0x08, 0x69, 0x71, 0xb1, 0x65, 0xa4, 0x26, 0xa6, 0xa4, 0x16, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0x70,
	0x1b, 0x09, 0xe9, 0x25, 0x16, 0x64, 0xea, 0x41, 0x65, 0x3d, 0xc0, 0x32, 0x41, 0x50, 0x15, 0x42,
	0x12, 0x5c, 0xec, 0xb9, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c,
	0x41, 0x30, 0xae, 0x52, 0x2c, 0x97, 0x08, 0xaa, 0xe1, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42,
	0xda, 0x68, 0xa6, 0x0b, 0x43, 0x4d, 0x87, 0x48, 0x13, 0x6b, 0xbc, 0x51, 0x14, 0xaa, 0xdb, 0x83,
	0x21, 0x7e, 0x16, 0x72, 0xe6, 0xe2, 0x41, 0x16, 0x16, 0x92, 0x00, 0x9b, 0x8e, 0xc5, 0x97, 0x52,
	0x92, 0x58, 0x64, 0x20, 0x6e, 0x48, 0x62, 0x03, 0x07, 0x8f, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0xcb, 0xbe, 0xd2, 0xa3, 0x5b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HelloTencentServiceClient is the client API for HelloTencentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloTencentServiceClient interface {
	// HelloTencent Stub
	HelloTencent(ctx context.Context, in *HelloTencentRequest, opts ...grpc.CallOption) (*HelloTencentResponse, error)
}

type helloTencentServiceClient struct {
	cc *grpc.ClientConn
}

func NewHelloTencentServiceClient(cc *grpc.ClientConn) HelloTencentServiceClient {
	return &helloTencentServiceClient{cc}
}

func (c *helloTencentServiceClient) HelloTencent(ctx context.Context, in *HelloTencentRequest, opts ...grpc.CallOption) (*HelloTencentResponse, error) {
	out := new(HelloTencentResponse)
	err := c.cc.Invoke(ctx, "/api.HelloTencentService/HelloTencent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloTencentServiceServer is the server API for HelloTencentService service.
type HelloTencentServiceServer interface {
	// HelloTencent Stub
	HelloTencent(context.Context, *HelloTencentRequest) (*HelloTencentResponse, error)
}

// UnimplementedHelloTencentServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHelloTencentServiceServer struct {
}

func (*UnimplementedHelloTencentServiceServer) HelloTencent(ctx context.Context, req *HelloTencentRequest) (*HelloTencentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HelloTencent not implemented")
}

func RegisterHelloTencentServiceServer(s *grpc.Server, srv HelloTencentServiceServer) {
	s.RegisterService(&_HelloTencentService_serviceDesc, srv)
}

func _HelloTencentService_HelloTencent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloTencentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloTencentServiceServer).HelloTencent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.HelloTencentService/HelloTencent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloTencentServiceServer).HelloTencent(ctx, req.(*HelloTencentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HelloTencentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.HelloTencentService",
	HandlerType: (*HelloTencentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HelloTencent",
			Handler:    _HelloTencentService_HelloTencent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/hellotencent_service.proto",
}
