// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/rpc_common.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RetCode int32

const (
	// Please do not modify bellow error codes!!!
	RetCode_OK    RetCode = 0
	RetCode_FAIL  RetCode = 1
	RetCode_ERROR RetCode = 2
)

var RetCode_name = map[int32]string{
	0: "OK",
	1: "FAIL",
	2: "ERROR",
}

var RetCode_value = map[string]int32{
	"OK":    0,
	"FAIL":  1,
	"ERROR": 2,
}

func (x RetCode) String() string {
	return proto.EnumName(RetCode_name, int32(x))
}

func (RetCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ee07f870dd397de8, []int{0}
}

type RequestHeader struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	StartTime            uint64   `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestHeader) Reset()         { *m = RequestHeader{} }
func (m *RequestHeader) String() string { return proto.CompactTextString(m) }
func (*RequestHeader) ProtoMessage()    {}
func (*RequestHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee07f870dd397de8, []int{0}
}

func (m *RequestHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestHeader.Unmarshal(m, b)
}
func (m *RequestHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestHeader.Marshal(b, m, deterministic)
}
func (m *RequestHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestHeader.Merge(m, src)
}
func (m *RequestHeader) XXX_Size() int {
	return xxx_messageInfo_RequestHeader.Size(m)
}
func (m *RequestHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestHeader.DiscardUnknown(m)
}

var xxx_messageInfo_RequestHeader proto.InternalMessageInfo

func (m *RequestHeader) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *RequestHeader) GetStartTime() uint64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

type ResponseHeader struct {
	RequestId            string            `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	RespTime             uint64            `protobuf:"varint,2,opt,name=resp_time,json=respTime,proto3" json:"resp_time,omitempty"`
	RetCode              RetCode           `protobuf:"varint,3,opt,name=ret_code,json=retCode,proto3,enum=api.RetCode" json:"ret_code,omitempty"`
	ErrMsg               string            `protobuf:"bytes,4,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	Params               map[string]string `protobuf:"bytes,5,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ResponseHeader) Reset()         { *m = ResponseHeader{} }
func (m *ResponseHeader) String() string { return proto.CompactTextString(m) }
func (*ResponseHeader) ProtoMessage()    {}
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee07f870dd397de8, []int{1}
}

func (m *ResponseHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseHeader.Unmarshal(m, b)
}
func (m *ResponseHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseHeader.Marshal(b, m, deterministic)
}
func (m *ResponseHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseHeader.Merge(m, src)
}
func (m *ResponseHeader) XXX_Size() int {
	return xxx_messageInfo_ResponseHeader.Size(m)
}
func (m *ResponseHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseHeader proto.InternalMessageInfo

func (m *ResponseHeader) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *ResponseHeader) GetRespTime() uint64 {
	if m != nil {
		return m.RespTime
	}
	return 0
}

func (m *ResponseHeader) GetRetCode() RetCode {
	if m != nil {
		return m.RetCode
	}
	return RetCode_OK
}

func (m *ResponseHeader) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *ResponseHeader) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

type TracingInfo struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TracingInfo) Reset()         { *m = TracingInfo{} }
func (m *TracingInfo) String() string { return proto.CompactTextString(m) }
func (*TracingInfo) ProtoMessage()    {}
func (*TracingInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee07f870dd397de8, []int{2}
}

func (m *TracingInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TracingInfo.Unmarshal(m, b)
}
func (m *TracingInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TracingInfo.Marshal(b, m, deterministic)
}
func (m *TracingInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TracingInfo.Merge(m, src)
}
func (m *TracingInfo) XXX_Size() int {
	return xxx_messageInfo_TracingInfo.Size(m)
}
func (m *TracingInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TracingInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TracingInfo proto.InternalMessageInfo

type RequestContext struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestContext) Reset()         { *m = RequestContext{} }
func (m *RequestContext) String() string { return proto.CompactTextString(m) }
func (*RequestContext) ProtoMessage()    {}
func (*RequestContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee07f870dd397de8, []int{3}
}

func (m *RequestContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestContext.Unmarshal(m, b)
}
func (m *RequestContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestContext.Marshal(b, m, deterministic)
}
func (m *RequestContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestContext.Merge(m, src)
}
func (m *RequestContext) XXX_Size() int {
	return xxx_messageInfo_RequestContext.Size(m)
}
func (m *RequestContext) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestContext.DiscardUnknown(m)
}

var xxx_messageInfo_RequestContext proto.InternalMessageInfo

type DigestPb struct {
	Md5Hex               string   `protobuf:"bytes,1,opt,name=md5_hex,json=md5Hex,proto3" json:"md5_hex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DigestPb) Reset()         { *m = DigestPb{} }
func (m *DigestPb) String() string { return proto.CompactTextString(m) }
func (*DigestPb) ProtoMessage()    {}
func (*DigestPb) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee07f870dd397de8, []int{4}
}

func (m *DigestPb) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DigestPb.Unmarshal(m, b)
}
func (m *DigestPb) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DigestPb.Marshal(b, m, deterministic)
}
func (m *DigestPb) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DigestPb.Merge(m, src)
}
func (m *DigestPb) XXX_Size() int {
	return xxx_messageInfo_DigestPb.Size(m)
}
func (m *DigestPb) XXX_DiscardUnknown() {
	xxx_messageInfo_DigestPb.DiscardUnknown(m)
}

var xxx_messageInfo_DigestPb proto.InternalMessageInfo

func (m *DigestPb) GetMd5Hex() string {
	if m != nil {
		return m.Md5Hex
	}
	return ""
}

type EventDataPb struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventDataPb) Reset()         { *m = EventDataPb{} }
func (m *EventDataPb) String() string { return proto.CompactTextString(m) }
func (*EventDataPb) ProtoMessage()    {}
func (*EventDataPb) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee07f870dd397de8, []int{5}
}

func (m *EventDataPb) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventDataPb.Unmarshal(m, b)
}
func (m *EventDataPb) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventDataPb.Marshal(b, m, deterministic)
}
func (m *EventDataPb) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventDataPb.Merge(m, src)
}
func (m *EventDataPb) XXX_Size() int {
	return xxx_messageInfo_EventDataPb.Size(m)
}
func (m *EventDataPb) XXX_DiscardUnknown() {
	xxx_messageInfo_EventDataPb.DiscardUnknown(m)
}

var xxx_messageInfo_EventDataPb proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("api.RetCode", RetCode_name, RetCode_value)
	proto.RegisterType((*RequestHeader)(nil), "api.RequestHeader")
	proto.RegisterType((*ResponseHeader)(nil), "api.ResponseHeader")
	proto.RegisterMapType((map[string]string)(nil), "api.ResponseHeader.ParamsEntry")
	proto.RegisterType((*TracingInfo)(nil), "api.TracingInfo")
	proto.RegisterType((*RequestContext)(nil), "api.RequestContext")
	proto.RegisterType((*DigestPb)(nil), "api.DigestPb")
	proto.RegisterType((*EventDataPb)(nil), "api.EventDataPb")
}

func init() { proto.RegisterFile("api/rpc_common.proto", fileDescriptor_ee07f870dd397de8) }

var fileDescriptor_ee07f870dd397de8 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xdf, 0xab, 0xd3, 0x30,
	0x14, 0xc7, 0x6d, 0xbb, 0x75, 0xed, 0x99, 0xf7, 0x52, 0xc2, 0x05, 0x8b, 0x22, 0x96, 0x0a, 0x5a,
	0x7c, 0xa8, 0x30, 0x19, 0xfe, 0x78, 0x93, 0x6d, 0xb2, 0xa1, 0x63, 0x23, 0xec, 0xbd, 0x64, 0xed,
	0xb1, 0x06, 0x4d, 0x13, 0x93, 0x6c, 0x6c, 0xaf, 0xfe, 0xe5, 0xd2, 0x1f, 0x0f, 0x7b, 0xbc, 0x6f,
	0x27, 0x9f, 0x9c, 0x7c, 0xf2, 0x3d, 0x09, 0x3c, 0x30, 0xc5, 0xdf, 0x6b, 0x55, 0x16, 0xa5, 0x14,
	0x42, 0x36, 0xb9, 0xd2, 0xd2, 0x4a, 0xe2, 0x31, 0xc5, 0xd3, 0x2d, 0xdc, 0x51, 0xfc, 0x7b, 0x42,
	0x63, 0xd7, 0xc8, 0x2a, 0xd4, 0xe4, 0x25, 0x80, 0xee, 0x41, 0xc1, 0xab, 0xd8, 0x49, 0x9c, 0x2c,
	0xa4, 0xe1, 0x40, 0x36, 0x55, 0xbb, 0x6d, 0x2c, 0xd3, 0xb6, 0xb0, 0x5c, 0x60, 0xec, 0x26, 0x4e,
	0x36, 0xa2, 0x61, 0x47, 0x0e, 0x5c, 0x60, 0xfa, 0xcf, 0x85, 0x7b, 0x8a, 0x46, 0xc9, 0xc6, 0xe0,
	0xe3, 0x84, 0x2f, 0x20, 0xd4, 0x68, 0xd4, 0xad, 0x2f, 0x68, 0x41, 0xab, 0x23, 0x6f, 0x21, 0xd0,
	0x68, 0x8b, 0x52, 0x56, 0x18, 0x7b, 0x89, 0x93, 0xdd, 0xcf, 0x9e, 0xe6, 0x4c, 0xf1, 0x9c, 0xa2,
	0x5d, 0xc8, 0x0a, 0xe9, 0x44, 0xf7, 0x05, 0x79, 0x06, 0x13, 0xd4, 0xba, 0x10, 0xa6, 0x8e, 0x47,
	0xdd, 0x0d, 0x3e, 0x6a, 0xbd, 0x35, 0x35, 0xf9, 0x08, 0xbe, 0x62, 0x9a, 0x09, 0x13, 0x8f, 0x13,
	0x2f, 0x9b, 0xce, 0x5e, 0x0d, 0xe7, 0x6f, 0x23, 0xe6, 0xfb, 0xae, 0x63, 0xd5, 0x58, 0x7d, 0xa5,
	0x43, 0xfb, 0xf3, 0xcf, 0x30, 0xbd, 0xc1, 0x24, 0x02, 0xef, 0x37, 0x5e, 0x87, 0xf8, 0x6d, 0x49,
	0x1e, 0x60, 0x7c, 0x66, 0x7f, 0x4e, 0x7d, 0xe8, 0x90, 0xf6, 0x8b, 0x2f, 0xee, 0x27, 0x27, 0xbd,
	0x83, 0xe9, 0x41, 0xb3, 0x92, 0x37, 0xf5, 0xa6, 0xf9, 0x29, 0xd3, 0xa8, 0x7d, 0x92, 0x6e, 0xdc,
	0x85, 0x6c, 0x2c, 0x5e, 0x6c, 0xfa, 0x1a, 0x82, 0x25, 0xaf, 0xd1, 0xd8, 0xfd, 0xb1, 0x4d, 0x2e,
	0xaa, 0x79, 0xf1, 0x0b, 0x2f, 0x83, 0xdc, 0x17, 0xd5, 0x7c, 0x8d, 0x97, 0xd6, 0xb2, 0x3a, 0x63,
	0x63, 0x97, 0xcc, 0xb2, 0xfd, 0xf1, 0xdd, 0x1b, 0x98, 0x0c, 0x53, 0x13, 0x1f, 0xdc, 0xdd, 0xf7,
	0xe8, 0x09, 0x09, 0x60, 0xf4, 0xed, 0xeb, 0xe6, 0x47, 0xe4, 0x90, 0x10, 0xc6, 0x2b, 0x4a, 0x77,
	0x34, 0x72, 0x8f, 0x7e, 0xf7, 0xb9, 0x1f, 0xfe, 0x07, 0x00, 0x00, 0xff, 0xff, 0x2f, 0xa4, 0xe1,
	0xf9, 0xf4, 0x01, 0x00, 0x00,
}
